"""Runtime <-> UI wire protocol (design doc 01-core §10-§14)."""

from .control import (
    AckMsg,
    ActionMsg,
    ActionName,
    ControlClientMsg,
    ControlServerMsg,
    GotoProfileArgs,
    HelloMsg,
    JointTargetArgs,
    KeysMsg,
    SaveProfileArgs,
    SetInitialConditionArgs,
    SwitchArmArgs,
    TrackerSettingsArgs,
    parse_client_msg,
    validate_action_args,
)
from .external import (
    ARM_STATE_LAYOUT,
    EVENT_KINDS,
    EXTERNAL_NODE_ID,
    MAVIS_SCHEMA,
    PLACEHOLDERS,
    POLICY_OUTPUTS,
    RUNTIME_INPUTS,
    CameraAnnounce,
    DoraInfo,
    DoraMachineInfo,
    EventEnvelope,
    ExternalStatus,
    OnlineDaggerAnnounce,
    PolicyResetMsg,
    PolicySpecAnnounce,
    PolicySpecModel,
    SessionAnnounce,
    TrainerStatusAnnounce,
)
from .gello import (
    GelloBackend,
    GelloCalibrateOp,
    GelloCalibrateRequest,
    GelloCalibrateResult,
    GelloDeviceStatus,
    GelloDeviceTelemetry,
    GelloInfo,
    GelloPairInfo,
    GelloPreviewRequest,
    GelloPreviewResult,
    GelloPreviewStatus,
    GelloState,
    GelloViewpointMode,
)
from .hardware_monitor import (
    ArmMonitorStatus,
    ArmMonitorTelemetry,
    HardwareMonitorTelemetry,
    TwinOverlayStatus,
    TwinOverlayTelemetry,
)
from .keymap import (
    DISCRETE_CODES,
    HELD_CODES,
    HELD_MODIFIER_ACTIONS,
    KEYMAP,
    KeymapEntry,
    axis_map,
)
from .maintenance import (
    ArmMaintenanceOp,
    ArmMaintenanceRequest,
    ArmMaintenanceResult,
    MaintenancePath,
    MaintenancePhase,
    MaintenanceProgress,
    MaintenanceStatus,
    PrePositionPlan,
    RailSweepVerdict,
)
from .microphone import MicrophoneInfo, MicStatus
from .session import (
    DATASET_RE,
    SLUG_RE,
    START_FROM_RE,
    ActionFilterConfig,
    ArmStatusInfo,
    CameraInfo,
    DatasetExportInfo,
    DatasetExportRequest,
    DatasetInfo,
    DatasetLayoutInfo,
    DatasetNamespaceInfo,
    EpisodeInfo,
    GelloSessionConfig,
    Mode,
    OnlineDaggerConfig,
    OnlineDaggerSessionInfo,
    PolicyInfo,
    ProfileInfo,
    ReturnHomeResult,
    SceneInfo,
    SessionInfo,
    SessionSpec,
    WorkcellStatus,
)
from .telemetry import (
    ArmBringupTelemetry,
    ArmTelemetry,
    ClearanceItem,
    ControllerTelemetry,
    DaggerStatus,
    DatasetExportTelemetry,
    DatasetsTelemetry,
    EpisodeStatus,
    GelloTelemetry,
    GelloViewpointTelemetry,
    InferenceStatus,
    MicrophoneTelemetry,
    OnlineDaggerStatus,
    PoseMsg,
    SessionTelemetry,
    TelemetryMsg,
    TrackerSettingsMsg,
    TrackerTelemetry,
)

# Keep ``.telemetry`` above ``.tracker``: tracker reuses PoseMsg and telemetry
# embeds TrackerCalibrationStatus (telemetry imports tracker once PoseMsg exists).
from .tracker import (
    CalibrationKind,
    CalibrationOp,
    CalibrationPhase,
    CalibrationValidation,
    LighthouseStatus,
    TrackerCalibrationCommand,
    TrackerCalibrationStatus,
    YawGesturePoint,
    YawPointLabel,
)
from .video import (
    HEADER_FMT,
    HEADER_SIZE,
    RESERVED_STREAM_IDS,
    is_reserved_stream,
    pack_frame,
    unpack_header,
)

__all__ = [
    # control
    "ActionName",
    "HelloMsg",
    "KeysMsg",
    "ActionMsg",
    "AckMsg",
    "JointTargetArgs",
    "SaveProfileArgs",
    "SwitchArmArgs",
    "SetInitialConditionArgs",
    "TrackerSettingsArgs",
    "GotoProfileArgs",
    "ControlClientMsg",
    "ControlServerMsg",
    "parse_client_msg",
    "validate_action_args",
    # telemetry
    "PoseMsg",
    "ArmTelemetry",
    "ClearanceItem",
    "EpisodeStatus",
    "DatasetExportTelemetry",
    "DatasetsTelemetry",
    "OnlineDaggerStatus",
    "DaggerStatus",
    "InferenceStatus",
    "ArmBringupTelemetry",
    "SessionTelemetry",
    "TrackerSettingsMsg",
    "ControllerTelemetry",
    "TrackerTelemetry",
    "MicrophoneTelemetry",
    "GelloViewpointTelemetry",  # phase-15 (16-gello §8.3)
    "GelloTelemetry",
    "TelemetryMsg",
    # tracker calibration
    "CalibrationKind",
    "CalibrationPhase",
    "CalibrationOp",
    "YawPointLabel",
    "LighthouseStatus",
    "CalibrationValidation",
    "YawGesturePoint",
    "TrackerCalibrationStatus",
    "TrackerCalibrationCommand",
    # session
    "Mode",
    "START_FROM_RE",
    "DATASET_RE",
    "SLUG_RE",
    "SessionSpec",
    "SessionInfo",
    "ArmStatusInfo",
    "CameraInfo",
    "WorkcellStatus",
    "SceneInfo",
    "ProfileInfo",
    "PolicyInfo",
    "ReturnHomeResult",
    "ActionFilterConfig",
    "DatasetInfo",
    "DatasetExportInfo",
    "DatasetExportRequest",
    "EpisodeInfo",
    # Online DAgger + dataset layout (phase-14; 15-online-dagger §5/§7)
    "OnlineDaggerConfig",
    "OnlineDaggerSessionInfo",
    "DatasetLayoutInfo",
    "DatasetNamespaceInfo",
    # GELLO Manipulation (phase-15, 2026-09-09; 16-gello §8): the SessionSpec block, the
    # shared literals + device half (protocol.gello) and the /api/gello* REST models
    "GelloSessionConfig",
    "GelloBackend",
    "GelloDeviceStatus",
    "GelloState",
    "GelloViewpointMode",
    "GelloCalibrateOp",
    "GelloPreviewStatus",
    "GelloDeviceTelemetry",
    "GelloInfo",
    "GelloCalibrateRequest",
    "GelloCalibrateResult",
    "GelloPreviewRequest",
    "GelloPairInfo",
    "GelloPreviewResult",
    # microphone (phase-11)
    "MicStatus",
    "MicrophoneInfo",
    # external interface over dora (phase-12; 14-dora): spellings + JSON payloads
    "MAVIS_SCHEMA",
    "EXTERNAL_NODE_ID",
    "PLACEHOLDERS",
    "RUNTIME_INPUTS",
    "POLICY_OUTPUTS",
    "EVENT_KINDS",
    "ARM_STATE_LAYOUT",
    "PolicySpecModel",
    "CameraAnnounce",
    "OnlineDaggerAnnounce",
    "SessionAnnounce",
    "PolicySpecAnnounce",
    "TrainerStatusAnnounce",
    "PolicyResetMsg",
    "EventEnvelope",
    "ExternalStatus",
    "DoraMachineInfo",
    "DoraInfo",
    # hardware monitor + twin overlay (phase-09a)
    "ArmMonitorStatus",
    "ArmMonitorTelemetry",
    "TwinOverlayStatus",
    "TwinOverlayTelemetry",
    "HardwareMonitorTelemetry",
    # arm maintenance (phase-09b; home_rail + RailSweepVerdict phase-09c; the async
    # RailHomingJob models phase-09d - MaintenanceProgress / MaintenancePhase /
    # ArmMaintenanceOp are defined in .hardware_monitor and re-exported by .maintenance)
    "ArmMaintenanceOp",
    "MaintenancePath",
    "MaintenanceStatus",
    "MaintenancePhase",
    "ArmMaintenanceRequest",
    "PrePositionPlan",
    "RailSweepVerdict",
    "ArmMaintenanceResult",
    "MaintenanceProgress",
    # video
    "HEADER_FMT",
    "HEADER_SIZE",
    "RESERVED_STREAM_IDS",
    "pack_frame",
    "unpack_header",
    "is_reserved_stream",
    # keymap
    "KeymapEntry",
    "KEYMAP",
    "HELD_CODES",
    "DISCRETE_CODES",
    "HELD_MODIFIER_ACTIONS",
    "axis_map",
]
